done changes welcome file 1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -104,9 +104,6 @@ jobs:
           php-version: 8.2
           extensions: mbstring, bcmath, intl, pdo, tokenizer, xml
 
-      - name: Install Composer dependencies
-        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
-
       - name: Build Frontend
         uses: actions/setup-node@v3
         with:
@@ -129,19 +126,19 @@ jobs:
               sudo mkdir /var/www/html/laravel-demo
               sudo chown  -R $SERVER_USER:$SERVER_USER /var/www/html/laravel-demo
               sudo chmod 0777 /var/www/html/laravel-demo
-              cd /var/www/html/laravel-demo || { echo "❌ Directory missing"; exit 1; }
+              cd /var/www/html/laravel-demo || { echo "Directory missing"; exit 1; }
 
               
               if [ -d ".git" ]; then
-                echo "🔄 Updating existing repo..."
+                echo "Updating existing repo..."
                 git reset --hard
                 git pull origin main
               else
-                echo "📥 Cloning repo for the first time..."
+                echo "Cloning repo for the first time..."
                 git clone https://github.com/hardik17tech/laravel-demo-ci-cd.git .
               fi
               
-              echo "📦 Installing PHP dependencies..."
+              echo "Installing PHP dependencies..."
               composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader && \
 
               echo "🛠 Running migrations & caching..."
@@ -150,13 +147,10 @@ jobs:
               php artisan route:cache && \
               php artisan view:cache && \
 
-              echo "🔄 Restarting PHP-FPM if available..."
+              echo "Restarting PHP-FPM if available..."
               sudo systemctl restart php8.3-fpm || true
 
-              echo "✅ Deployment finished!"
-              echo "📂 Project deployed to: $(pwd)"
-              ls -la
-
+              echo "Deployment finished!"              
             '
 
 
